version: '3.8'

services:
  task_service:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn src.main:app --host 0.0.0.0'
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DB_URL}
    depends_on:
      - db
    networks:
      - task-net

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=task
    networks:
      - task-net

volumes:
  postgres_data:

networks:
  task-net:
    driver: bridge